version: '3.8'

networks:
  laravel:


services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"
    networks:
      - laravel

    depends_on:
        - database

  database:
#    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 7b6mXCmBKgyqCtSj53JF
      MYSQL_DATABASE: lucky6
      MYSQL_USER: user
      MYSQL_PASSWORD: 7b6mXCmBKgyqCtSj53JF
    ports:
      - '3306:3306'
    networks:
      - laravel
    volumes:
     - ./mysql:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - laravel

#  swoole:
#    # image: phpswoole/swoole:latest
#    image: phpswoole/swoole:4.5.2-php7.4
#    environment:
##      - DOCKER=1
##      - HOST=0.0.0.0
##      - HOSTNAME=docker.local
#      - PORT=8080
#      - SWOOLE_HTTP_HOST=0.0.0.0 # required for Laravel swoole
#      - SWOOLE_HTTP_WEBSOCKET=true # required for Laravel swoole websocket
#    command: php /workdir/serve-file.php start
#    # command: php /workdir/client.php start # broken without additional async extension
#    # command: php /workdir/channel.php start # broken without additional async extension
#    # command: php /workdir/process.php start
#    # command: php /workdir/router.php start
#    # command: php /workdir/websocket.php start
#    # command: php /workdir/slim.php start
#    # command: php /workdir/event-source.php start
#    # command: php /workdir/users/artisan serve --host=0.0.0.0 --port=1215 # Laravel no swoole
#    # command: php /workdir/users/artisan swoole:http start # Laravel with swoole
#    ports:
#      - "8080:8080"
#      - "1215:1215" # Laravel port
#    volumes:
#      - ./:/var/www/html

  cron:
    build:
      context: .
      dockerfile: cron.dockerfile
    container_name: cron
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel




volumes:
  dbdata: